// AUTO-GENERATED by scripts/build-data.js — do not edit manually.
// Source: clients/pokemon-fables/series.json + series/*/episodes/*.json + shop.json

import type { Series, ShopProduct } from "./types";

export const SERIES: Series[] = [
  {
    "id": "flames-of-our-lives",
    "title": "Flames of Our Lives",
    "tagline": "Love burns. So does Charizard.",
    "genre": "Soap Opera • Drama • Comedy",
    "type": "Fire",
    "color": "#E8651A",
    "accent": "#FFB347",
    "bg": "linear-gradient(135deg, #E8651A 0%, #C41E3A 50%, #8B1A1A 100%)",
    "desc": "The most dramatic saga in Verdant Valley. Fire-types with too many feelings, secrets that burn hotter than any Flamethrower, and a Venusaur who just wants answers.",
    "status": "Airing",
    "epCount": 5,
    "episodes": [
      {
        "id": 1,
        "slug": "the-nap-that-changed-everything",
        "title": "The Nap That Changed Everything",
        "cards": [
          {
            "name": "Charizard V (SAR)",
            "set": "VSTAR Universe",
            "artist": "Oswaldo KATO",
            "emoji": "🔥",
            "image": "/images/cards/charizardVSAR.jpg",
            "affiliateUrl": "#"
          }
        ],
        "products": [
          {
            "name": "VSTAR Universe Booster Box",
            "url": "#",
            "price": "~$85",
            "tag": "Booster",
            "emoji": "📦"
          },
          {
            "name": "Ultra Pro Sleeves (100ct)",
            "url": "#",
            "price": "~$9",
            "tag": "Sleeves",
            "emoji": "🛡️"
          },
          {
            "name": "9-Pocket Pro Binder",
            "url": "#",
            "price": "~$25",
            "tag": "Binder",
            "emoji": "📒"
          }
        ],
        "status": "live",
        "junior": {
          "scene": "A sunny meadow in Verdant Valley",
          "paragraphs": [
            {
              "t": "p",
              "c": "Charizard was the biggest, strongest Pokémon in Verdant Valley. He could fly super fast. He could breathe fire that was SO hot. He was amazing."
            },
            {
              "t": "p",
              "c": "But right now? He was taking a nap."
            },
            {
              "t": "p",
              "c": "Not just any nap. The BIGGEST nap. He was curled up in the grass like a giant orange cat, snoring so loud that the leaves were falling off the trees. His tail flame went flicker... flicker... flicker..."
            },
            {
              "t": "p",
              "c": "Venusaur was watching from behind a hill. Venusaur was big and green and covered in flowers, and right now he was very, VERY grumpy."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Are you KIDDING me? He burned down half the meadow last week! And now he's sleeping here like nothing happened!\""
            },
            {
              "t": "p",
              "c": "Everyone in the valley thought Charizard was selfish. He never helped with anything. He never came to the valley meetings. He just flew around and napped and sometimes accidentally set things on fire."
            },
            {
              "t": "p",
              "c": "But here's the secret. The BIG secret."
            },
            {
              "t": "p",
              "c": "Charizard wasn't being lazy. He was EXHAUSTED."
            },
            {
              "t": "p",
              "c": "Every single night, when everyone was asleep, Charizard flew to the caves on the north side of the valley. A big storm had knocked down the trees near the caves, and all the baby Pokémon who lived there were cold. Really, really cold."
            },
            {
              "t": "p",
              "c": "So Charizard used his fire breath — very carefully, very gently — to keep the caves warm all night long. He kept the little Charmanders warm. He kept the shivering Eevees warm. He even kept a very grumpy Snorlax warm, even though Snorlax said he was \"fine\" (he was NOT fine)."
            },
            {
              "t": "p",
              "c": "But Charizard never told anyone. He was too proud. He didn't want anyone to think he was... nice."
            },
            {
              "t": "a",
              "c": "— a leaf floats gently across the meadow —"
            },
            {
              "t": "p",
              "c": "Back on the hill, Venusaur squinted his eyes. He noticed something weird. The burn marks on Charizard's claws didn't look like accident burns. They looked like WORK burns. Like he'd been doing something careful and hard, over and over again."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Hmm. Something's going on with that big lizard... and I'm going to find out WHAT.\""
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        },
        "full": {
          "scene": "A sunlit clearing in Verdant Valley",
          "paragraphs": [
            {
              "t": "p",
              "c": "Charizard — once the most feared, most powerful, most dramatic fire-breather in all of Verdant Valley — was… taking a nap."
            },
            {
              "t": "p",
              "c": "Not just any nap. A legendary nap. Curled up like a giant orange cat, tail flame flickering lazily, snoring loud enough to shake the leaves off the trees. Some of those trees? Already a little burnt. Nobody talks about that."
            },
            {
              "t": "p",
              "c": "In the background, Venusaur watched from behind a hill, squinting."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Unbelievable. He burns down half the meadow LAST Tuesday, doesn't apologize, and now he's sleeping like a baby in the SAME meadow. The audacity.\""
            },
            {
              "t": "p",
              "c": "But here's the thing nobody knew — Charizard wasn't just being lazy. He was exhausted."
            },
            {
              "t": "p",
              "c": "For weeks, he'd been secretly flying across the valley every night, using his Heat Blast to keep the northern caves warm for the baby Pokémon who'd lost their homes after the big storm. The little Charmanders, the shivering Eevees, even a very grumpy Snorlax who refused to admit he was cold."
            },
            {
              "t": "p",
              "c": "He never told anyone. Too proud. Too stubborn. Too… Charizard."
            },
            {
              "t": "p",
              "c": "So while the valley gossiped about the \"selfish dragon,\" Charizard just curled up tighter, let the sun warm his wings, and dreamed of a world where nobody needed saving anymore."
            },
            {
              "t": "a",
              "c": "— a leaf blows gently across the clearing —"
            },
            {
              "t": "p",
              "c": "Venusaur narrowed his eyes. Something didn't add up. The scorch marks on Charizard's claws weren't from recklessness — they were from work. Long, careful, exhausting work."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Something's going on with that oversized lizard… and I'm going to find out what.\""
            },
            {
              "t": "end",
              "c": "To be continued…"
            }
          ]
        }
      },
      {
        "id": 2,
        "slug": "the-witch-who-knew-too-much",
        "title": "The Witch Who Knew Too Much",
        "cards": [
          {
            "name": "Mismagius ex",
            "set": "M2 (036/080 RR)",
            "artist": "5ban Graphics",
            "emoji": "👻",
            "affiliateUrl": "#"
          },
          {
            "name": "Genesect V",
            "set": "VSTAR Universe (102/172 RR)",
            "artist": "PLANETA Tsuji",
            "emoji": "🤖",
            "affiliateUrl": "#"
          }
        ],
        "products": [
          {
            "name": "Pokémon 151 Bundle (6 packs)",
            "url": "#",
            "price": "~$35",
            "tag": "Booster",
            "emoji": "🎴"
          },
          {
            "name": "Ultra Pro Sleeves (100ct)",
            "url": "#",
            "price": "~$9",
            "tag": "Sleeves",
            "emoji": "🛡️"
          },
          {
            "name": "LED Magnifying Loupe",
            "url": "#",
            "price": "~$12",
            "tag": "Gear",
            "emoji": "🔍"
          }
        ],
        "status": "live",
        "junior": {
          "scene": "The edge of the valley, nighttime. Fog everywhere.",
          "paragraphs": [
            {
              "t": "p",
              "c": "Venusaur couldn't sleep. He kept thinking about Charizard and those weird burn marks on his claws."
            },
            {
              "t": "p",
              "c": "So tonight, he decided to follow Charizard. Like a detective! A really big, really slow, really loud detective."
            },
            {
              "t": "p",
              "c": "The sun went down. The stars came out. And sure enough — Charizard woke up, stretched his wings, and flew north."
            },
            {
              "t": "p",
              "c": "Venusaur tried to sneak through the forest after him. But sneaking is hard when you weigh as much as a car."
            },
            {
              "t": "p",
              "c": "CRUNCH. SNAP. CRUNCH."
            },
            {
              "t": "q",
              "speaker": "???",
              "c": "\"You know, for a spy, you're really, REALLY bad at this.\""
            },
            {
              "t": "p",
              "c": "Venusaur froze. That voice came from... everywhere? He looked left. He looked right. He looked up."
            },
            {
              "t": "p",
              "c": "And there she was."
            },
            {
              "t": "a",
              "c": "— purple mist swirls and sparkles fill the air —"
            },
            {
              "t": "p",
              "c": "Mismagius floated down from the treetops, covered in sparkles and glowing purple light. She was a Ghost-type who'd lived in the valley forever. Nobody knew where she came from. She just... showed up wherever something interesting was happening."
            },
            {
              "t": "p",
              "c": "Some Pokémon called her the Witch. She preferred \"Observer.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"You're following the big dragon, aren't you?\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"I'm INVESTIGATING. That's different.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Sure, sure. Very professional. Very sneaky. Not at all like a Tauros crashing through a gift shop.\""
            },
            {
              "t": "p",
              "c": "Venusaur's face got hot. His flower started blooming. That always happened when he was embarrassed."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Do you know what Charizard is doing every night?\""
            },
            {
              "t": "p",
              "c": "Mismagius stopped smiling. Her sparkles changed from pink to dark purple. She floated closer."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"I know EVERYTHING that happens in this valley at night. I know Charizard flies to the northern caves to keep the baby Pokémon warm. But that's not the scary part.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"There's a SCARY PART?\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Something new has come to the valley. Something made of metal. It has a cannon on its back. It doesn't eat. It doesn't sleep. It just flies around scanning everything. And it's heading straight for those caves.\""
            },
            {
              "t": "a",
              "c": "— SCREEEEECH! A metallic sound echoes from the mountains —"
            },
            {
              "t": "p",
              "c": "They both looked up. A streak of purple and silver light shot across the sky like a rocket. It wasn't a bird. It wasn't a Pokémon they'd ever seen. It moved like a machine — fast, sharp, and scary."
            },
            {
              "t": "p",
              "c": "Genesect. A robotic Pokémon with a giant cannon on its back, blasting through the sky straight toward the northern caves."
            },
            {
              "t": "p",
              "c": "Straight toward Charizard. Straight toward the babies."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"We have to warn Charizard! NOW!\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"WE? Oh no no no. I'm a ghost. I float and I watch. I don't DO running.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Mismagius. Please.\""
            },
            {
              "t": "p",
              "c": "She looked at him for a long moment. Then she sighed — a sigh that made all the flowers around them shiver."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Fine. But I'm floating the whole way. And if anything bad happens, I'm blaming you.\""
            },
            {
              "t": "p",
              "c": "And so the grumpiest Pokémon in the valley and the spookiest Pokémon in the valley started running (and floating) north as fast as they could."
            },
            {
              "t": "p",
              "c": "Behind them, the valley slept peacefully."
            },
            {
              "t": "p",
              "c": "Ahead of them, Charizard had no idea what was coming."
            },
            {
              "t": "p",
              "c": "And above them, Genesect's cannon glowed in the dark."
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        },
        "full": {
          "scene": "The edge of Verdant Valley, twilight. Fog rolling in.",
          "paragraphs": [
            {
              "t": "p",
              "c": "Venusaur couldn't sleep."
            },
            {
              "t": "p",
              "c": "It had been three days since he'd noticed the scorch marks on Charizard's claws. Three days of watching that overgrown fire hazard nap in the meadow like he didn't have a care in the world. Three days of knowing something was off and not being able to prove it."
            },
            {
              "t": "p",
              "c": "So tonight, Venusaur did something he'd never done in fourteen years of living in this valley. He followed someone."
            },
            {
              "t": "p",
              "c": "The moment the sun dipped below the ridge and the last Pidgey stopped chirping, Charizard stirred. Stretched his wings. Yawned a column of fire that nearly scorched a passing Butterfree — \"SORRY!\" — and launched into the sky heading north."
            },
            {
              "t": "p",
              "c": "Venusaur lumbered after him on the ground, sticking to the tree line, moving as quietly as a four-hundred-pound dinosaur plant possibly could. Which was not quietly at all."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"You know, for a spy, you're absolutely terrible at this.\""
            },
            {
              "t": "p",
              "c": "The voice came from everywhere and nowhere. It floated down like silk made of smoke, curling around his ears with a warmth that felt... wrong. Too warm. The kind of warm that makes you forget what you were doing."
            },
            {
              "t": "a",
              "c": "— the fog parts, and a swirl of purple mist takes shape —"
            },
            {
              "t": "p",
              "c": "Mismagius descended from the canopy, trailing sparkles and pink crystal light like she was her own special effect. Her eyes — those impossible red eyes — locked onto Venusaur with the expression of someone who had been watching this whole situation unfold for weeks and was deeply entertained by it."
            },
            {
              "t": "p",
              "c": "Mismagius was the valley's oldest mystery. Nobody knew when she'd arrived. Nobody knew where she lived. She showed up at every major event — every argument, every breakup, every midnight scandal — and watched from the shadows with that little smile."
            },
            {
              "t": "p",
              "c": "Some Pokémon called her the Oracle. Others called her the Witch. Snorlax once called her \"deeply unsettling,\" which was the most words Snorlax had used in a single sentence all year."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"You're following the dragon.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"I'm investigating. There's a difference.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Mmm. Of course. Very official. Very dignified. Very much stumbling through bushes at midnight like a confused Tauros.\""
            },
            {
              "t": "p",
              "c": "Venusaur felt his face go hot. Which, for a Grass-type, meant his flower actually started to bloom a little. Embarrassing."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Do you know what he's doing? The night flights? The scorch marks?\""
            },
            {
              "t": "p",
              "c": "Mismagius tilted her head. The sparkles around her shifted from pink to deep violet. When she spoke, her voice dropped to something almost serious."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"I know everything that happens in this valley after dark, Venusaur. Everything. I know that Charizard flies north every single night. I know what he does when he gets there. And I know that you're not going to like the answer — not because it's bad, but because it's going to make you feel guilty for every rotten thing you've said about him.\""
            },
            {
              "t": "p",
              "c": "She drifted closer. The air around her got colder. The sparkles died."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"He's not just keeping them warm. He's guarding them. Something has been approaching the northern ridge for the past two weeks. Something none of us have ever seen before. Metal body. Red eyes. A cannon on its back. It doesn't eat. It doesn't sleep. It just... scans. Like it's searching for something.\""
            },
            {
              "t": "p",
              "c": "Venusaur felt the vines on his back tighten involuntarily."
            },
            {
              "t": "a",
              "c": "— a distant metallic screech echoes from the northern mountains —"
            },
            {
              "t": "p",
              "c": "Both of them turned toward the sound. Above the treeline, a streak of purple and silver light cut across the sky like a comet with a grudge. Fast. Precise. Nothing natural about it."
            },
            {
              "t": "p",
              "c": "Genesect had arrived in Verdant Valley. Not walking. Not flying in the way birds fly — no grace, no wind. It moved like a machine that had calculated the most efficient trajectory between two points and simply executed. The cannon on its back glowed a sickly violet, scanning the terrain below."
            },
            {
              "t": "p",
              "c": "It was heading straight for the northern caves. Straight for Charizard."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"We have to warn him.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"We? Oh no no no. You have to warn him. I'm an observer. I observe. I comment. I occasionally make things sparkle. I do not do... running.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Mismagius. Please.\""
            },
            {
              "t": "p",
              "c": "She looked at him. Really looked at him — past the grumpy exterior and the judgmental squinting and the fourteen years of loudly complaining about Charizard at every community meeting."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"...You actually care about him, don't you?\""
            },
            {
              "t": "p",
              "c": "Venusaur said nothing. His flower bloomed a little more."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Fine. But I'm floating. And if I die, I'm haunting you specifically.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"You're already a ghost.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Then I'll haunt you harder.\""
            },
            {
              "t": "p",
              "c": "They moved north. Venusaur running — actually running — for the first time in years. Mismagius gliding beside him, trailing purple light and looking like the most reluctant hero in the history of Verdant Valley."
            },
            {
              "t": "p",
              "c": "Behind them, the valley slept peacefully. Ahead of them, a dragon who didn't know he needed saving was about to meet something that didn't know it needed stopping."
            },
            {
              "t": "p",
              "c": "And above them all, Genesect's cannon hummed."
            },
            {
              "t": "end",
              "c": "To be continued…"
            }
          ]
        }
      },
      {
        "id": 3,
        "slug": "the-ground-beneath-their-feet",
        "title": "The Ground Beneath Their Feet",
        "cards": [
          {
            "name": "Team Rocket's Dugtrio",
            "set": "M2a (083/193)",
            "artist": "KEIICHIRO ITO",
            "emoji": "💥",
            "image": "/images/cards/dugtrio.jpg",
            "affiliateUrl": "#"
          }
        ],
        "products": [
          {
            "name": "M2a Space-Time Smackdown Box",
            "url": "#",
            "price": "~$45",
            "tag": "Booster",
            "emoji": "🌌"
          },
          {
            "name": "KMC Perfect Fit Inner Sleeves (100ct)",
            "url": "#",
            "price": "~$6",
            "tag": "Sleeves",
            "emoji": "🛡️"
          },
          {
            "name": "BCW Card Storage Box (3200ct)",
            "url": "#",
            "price": "~$18",
            "tag": "Gear",
            "emoji": "📦"
          }
        ],
        "status": "live",
        "junior": {
          "scene": "The northern caves, night. The ground is shaking.",
          "paragraphs": [
            {
              "t": "p",
              "c": "Venusaur and Mismagius ran (and floated) as fast as they could toward the northern caves. They could see Charizard's fire glowing in the distance."
            },
            {
              "t": "p",
              "c": "But something was wrong. The ground was shaking."
            },
            {
              "t": "p",
              "c": "Not a little shake. A BIG shake. The kind of shake where the trees wiggle and the rocks bounce and Venusaur almost fell on his face THREE times."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"What is HAPPENING?!\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"The ground is breaking apart! Something is tunneling underneath us!\""
            },
            {
              "t": "a",
              "c": "— CRACK! RUMBLE! CRASH! The cave entrance splits in two —"
            },
            {
              "t": "p",
              "c": "They burst through the trees and saw the caves. And it was BAD."
            },
            {
              "t": "p",
              "c": "Genesect was flying above the caves, firing laser blasts from its cannon. BOOM! BOOM! Rocks exploded everywhere. The baby Pokémon inside were crying."
            },
            {
              "t": "p",
              "c": "And from BELOW the caves, three brown heads popped out of the ground. Dugtrio! But this wasn't a normal Dugtrio. It had mean, angry eyes. And on the rocks near the tunnel entrance, someone had painted a big red letter R."
            },
            {
              "t": "p",
              "c": "Team Rocket."
            },
            {
              "t": "p",
              "c": "Dugtrio was digging tunnels UNDER the caves, making the floor collapse! Genesect attacked from above. Dugtrio destroyed from below. It was a trap!"
            },
            {
              "t": "p",
              "c": "Charizard was already fighting. He was blasting fire at Genesect, trying to keep it away from the cave entrance. But he was tired. So, SO tired. He'd been warming the caves all night, and now he had to fight too."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "\"Get... AWAY from them!\""
            },
            {
              "t": "p",
              "c": "His fire blast hit Genesect, but Genesect barely flinched. Its metal body just glowed red for a second, and then it fired back. Charizard dodged, but just barely."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"CHARIZARD! We're here! We came to help!\""
            },
            {
              "t": "p",
              "c": "Charizard looked down and saw Venusaur and Mismagius. His eyes went wide. For a second, he looked like he might cry. But Charizards don't cry. They just... breathe fire a little harder."
            },
            {
              "t": "p",
              "c": "They made a plan in ten seconds flat. Charizard took the sky — fire blasts to keep Genesect busy. Venusaur sent his vines deep into the ground, wrapping around rocks and roots, holding the cave floor together like a giant green net. And Mismagius? She turned invisible and floated into Dugtrio's tunnels."
            },
            {
              "t": "p",
              "c": "Dugtrio saw glowing purple eyes in the darkness of its own tunnel. Then two eyes. Then TEN eyes. Mismagius made it look like an army of ghosts was coming straight at it."
            },
            {
              "t": "q",
              "speaker": "Dugtrio",
              "c": "\"AHHHHH!\""
            },
            {
              "t": "p",
              "c": "Dugtrio freaked out and tunneled away SO fast it left a dust cloud shaped like itself. Genesect, seeing its partner flee, fired one last shot and rocketed into the sky, disappearing in a flash of purple light."
            },
            {
              "t": "p",
              "c": "The caves were safe. The babies were safe. Venusaur's vines were holding everything together. Charizard landed hard, exhausted, and for the first time ever... he looked at Venusaur and said:"
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "\"...Thanks.\""
            },
            {
              "t": "p",
              "c": "Venusaur's flower bloomed so hard it almost exploded."
            },
            {
              "t": "a",
              "c": "— the dust settles and moonlight returns to the caves —"
            },
            {
              "t": "p",
              "c": "But Mismagius wasn't smiling. She floated back from the tunnels holding something she'd found deep underground. A metal badge. Shiny. Cold. With a big red R stamped on it."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"This wasn't just a random attack. Those two were sent here. By Team Rocket. And if they sent two... they'll send more.\""
            },
            {
              "t": "p",
              "c": "Charizard, Venusaur, and Mismagius looked at each other. The babies were safe tonight. But what about tomorrow night? And the night after that?"
            },
            {
              "t": "p",
              "c": "Somewhere far away, in a building with no windows, a screen flickered. A grunt in a black uniform watched Dugtrio and Genesect retreat on a radar map. He picked up a phone."
            },
            {
              "t": "q",
              "speaker": "???",
              "c": "\"Send the next team. The valley has more fight than we expected.\""
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        },
        "full": {
          "scene": "The northern caves, deep night. The earth itself is trembling.",
          "paragraphs": [
            {
              "t": "p",
              "c": "They heard the caves before they saw them."
            },
            {
              "t": "p",
              "c": "A low, grinding vibration rolled through the forest floor — not thunder, not wind, but something beneath. Something deliberate. The trees swayed without breeze. Pebbles danced on flat stones like water on a hot pan. Venusaur felt it in his roots, in the deep places where instinct lived."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"The ground is wrong. Something is tunneling beneath us.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"Not something. Someone. And they've been at it for a while.\""
            },
            {
              "t": "p",
              "c": "They broke through the tree line and the world opened into a nightmare."
            },
            {
              "t": "a",
              "c": "— an explosion of rock and light above the northern caves —"
            },
            {
              "t": "p",
              "c": "Genesect hung in the air above the cave entrance like a malevolent star, its cannon cycling through violet charges and releasing them in precise, devastating arcs. Each blast struck the cliff face with surgical accuracy — not random destruction, but calculated demolition. It was taking the caves apart piece by piece."
            },
            {
              "t": "p",
              "c": "And below — below was worse."
            },
            {
              "t": "p",
              "c": "Three brown heads emerged from a fissure in the earth twenty meters from the cave mouth. Dugtrio. But not wild — Venusaur could see it immediately. The movements were too coordinated, too purposeful. This creature answered to someone. And carved into the rock wall beside the tunnel it had emerged from, fresh and unmistakable, was a symbol: a crimson R."
            },
            {
              "t": "p",
              "c": "Team Rocket. The name carried weight even here, even in a valley that had spent decades pretending the outside world couldn't touch it."
            },
            {
              "t": "p",
              "c": "Dugtrio worked in silence, boring through the substrate beneath the caves with mechanical efficiency, each tunnel weakening the foundation a little more. Genesect attacked from above. Dugtrio eroded from below. A pincer operation executed with the cold logic of machines and the cruelty of people who built them."
            },
            {
              "t": "p",
              "c": "And in the middle of it all, Charizard fought alone."
            },
            {
              "t": "p",
              "c": "He was magnificent and he was failing. Fire Blast after Fire Blast lit up the night sky, driving Genesect back, buying seconds for the cave entrance. But Charizard had been warming those caves for hours before the attack began. His flame was already low. His wings trembled on every upstroke. A blast from Genesect's cannon caught his left shoulder and he spiraled, caught himself, and climbed again — slower this time."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "\"Come on, you metal freak. COME ON.\""
            },
            {
              "t": "p",
              "c": "Inside the caves, Venusaur could hear them — the babies. Charmanders crying. Eevees pressed against the back wall. That stubborn Snorlax, finally awake and terrified, trying to shield the smaller ones with his body. The floor beneath them cracking."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"We need to move. NOW.\""
            },
            {
              "t": "p",
              "c": "What happened next took eleven seconds. Venusaur had never moved that fast in his life and probably never would again."
            },
            {
              "t": "p",
              "c": "He charged. Four hundred pounds of Grass-type fury barreling toward the cave mouth. His vines — all of them, every tendril he had — shot into the ground like anchors, threading through rock and root and clay, weaving a lattice beneath the cave floor. It wouldn't hold forever. But it would hold long enough."
            },
            {
              "t": "p",
              "c": "Charizard saw Venusaur arrive and his eyes went wide. For one unguarded moment, the proud dragon looked like what he actually was — exhausted, overwhelmed, and unspeakably grateful that he wasn't alone anymore."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "\"Venusaur? What are you —\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"SHUT UP AND KEEP FLYING! I've got the ground!\""
            },
            {
              "t": "p",
              "c": "Charizard shut up and kept flying. Overhead, his fire renewed — not because his energy had returned, but because something fiercer had taken the place of exhaustion. He wasn't fighting alone. That changed things."
            },
            {
              "t": "p",
              "c": "Mismagius, meanwhile, had already vanished."
            },
            {
              "t": "p",
              "c": "She phased through solid rock and descended into Dugtrio's tunnel network. In the absolute darkness sixty feet below the surface, she let herself become what Ghost-types truly are when they stop performing for an audience. Her form dissolved into pure spectral energy — eyes multiplying, voice splitting into layered harmonics, the temperature dropping so fast that frost crystallized on the tunnel walls."
            },
            {
              "t": "p",
              "c": "Dugtrio turned and saw the darkness behind it fill with light. Not warm light. The cold, violet, ancient light of something that existed before the concept of mercy was invented."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"You are in my valley. You are beneath my ground. And I am the thing that lives in the dark down here.\""
            },
            {
              "t": "p",
              "c": "Dugtrio fled. There was no other word for it. All three heads screamed in unison and the creature burrowed away so fast it left a vacuum in its wake, the tunnel collapsing behind it. Up above, Genesect registered its partner's retreat on whatever internal systems governed its tactical decisions. It fired one final volley — a parting shot that cracked the cliff face above the cave entrance — and rocketed skyward, disappearing into the clouds like a violet comet."
            },
            {
              "t": "p",
              "c": "Silence."
            },
            {
              "t": "p",
              "c": "Charizard landed hard at the cave mouth, wings folded, chest heaving. Venusaur's vines still held the ground together, roots trembling with the strain. Inside the caves, a Charmander peeked out from behind Snorlax's belly. Then an Eevee. Then another."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "\"...You came.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Of course I came, you idiot. You think I'd let you have all the dramatic moments to yourself?\""
            },
            {
              "t": "p",
              "c": "Charizard laughed. It was a rough, broken sound — half exhaustion, half something that had been wound too tight for too long finally releasing. His tail flame flickered. Venusaur's flower bloomed in the dark."
            },
            {
              "t": "a",
              "c": "— moonlight breaks through the dust, illuminating the ruined cave entrance —"
            },
            {
              "t": "p",
              "c": "Mismagius emerged from the ground moments later, her usual sparkles dimmed, her expression something none of them had seen before. Serious. Genuinely, deeply serious."
            },
            {
              "t": "p",
              "c": "In her spectral grasp, she held a small metal object. A badge. Matte black with a crimson R embossed on its surface. It was warm to the touch and hummed faintly — a transmitter."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"This wasn't a raid. It was a reconnaissance mission. They weren't trying to destroy the caves. They were testing defenses. Mapping the valley. And this —\" she held up the badge, \"— has been broadcasting our location since the moment they arrived.\""
            },
            {
              "t": "p",
              "c": "The three of them stood in the wreckage of the cave entrance, surrounded by sleeping babies and broken stone, and understood the same thing at the same time: tonight was not the end of something. It was the beginning."
            },
            {
              "t": "p",
              "c": "Somewhere beyond the mountains, in a facility that didn't appear on any map, a monitor displayed three thermal signatures clustered around the northern caves. A grunt in a black uniform picked up a secure line."
            },
            {
              "t": "q",
              "speaker": "???",
              "c": "\"Dugtrio and Genesect have been repelled. But we have the data. The valley is defended, but not by much. Three hostiles. One fire, one grass, one ghost. Recommend escalating to Phase Two.\""
            },
            {
              "t": "p",
              "c": "The line crackled. Then a voice — calm, measured, the kind of voice that had never needed to raise itself:"
            },
            {
              "t": "q",
              "speaker": "???",
              "c": "\"Approved. Send the next unit. And this time, don't underestimate the dragon.\""
            },
            {
              "t": "end",
              "c": "To be continued…"
            }
          ]
        }
      },
      {
        "id": 4,
        "slug": "the-inspector-arrives",
        "title": "The Inspector Arrives",
        "cards": [
          {
            "name": "メタング (Metang) 092/083 AR",
            "set": "M4",
            "artist": "Kurata So",
            "emoji": "🔩",
            "image": "/images/cards/metang092-083.jpg"
          }
        ],
        "status": "live",
        "junior": {
          "scene": "High above Verdant Valley, a steel-clawed inspector checks the cave ceiling — and finds something very wrong.",
          "paragraphs": [
            {
              "t": "p",
              "c": "High above the northern caves, a Metang hovered beside the rock face. It was wearing a tiny hard hat. Well — sort of. It had magnetically clamped a yellow construction marker to its head. That counted."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "Structural survey. Section Seven. All clear so— CLUNK."
            },
            {
              "t": "a",
              "c": "CRACK. A chunk of cave ceiling broke off and bonked Metang right in the claws."
            },
            {
              "t": "p",
              "c": "Metang stared at the chunk. Then at the ceiling. Then at its clipboard. There was a very long crack running along the cave wall — all the way down to the floor."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "That is... not in my report."
            },
            {
              "t": "a",
              "c": "Deep below, something was RUMBLING. The ground shook. Dust fell like snow."
            },
            {
              "t": "p",
              "c": "Inside the cave, the baby Pokémon were fully awake now. A tiny Larvitar was crying. A baby Snorlax was sitting on a baby Jigglypuff. Nobody was happy."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "Nobody panic. I said NOBODY PANIC."
            },
            {
              "t": "a",
              "c": "Everyone panicked. WAAAH. BONK. SQUEAK."
            },
            {
              "t": "p",
              "c": "Metang pressed one cold steel claw against the cracked wall and felt it. The vibrations were coming from below — rhythmic, deliberate. Not an earthquake. Something was DIGGING."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "Unauthorized excavation detected. This is a hard hat zone."
            },
            {
              "t": "a",
              "c": "Metang reached out one claw and knocked firmly on the cave wall. Three times. CLANG. CLANG. CLANG."
            },
            {
              "t": "p",
              "c": "The digging stopped. For exactly two seconds."
            },
            {
              "t": "p",
              "c": "Then it got FASTER."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "...They are not going to fill out a permit, are they."
            },
            {
              "t": "a",
              "c": "Outside, Venusaur and Mismagius were still facing Team Rocket's Dugtrio. Three heads. Three smug grins. One very large tunnel entrance behind them."
            },
            {
              "t": "q",
              "speaker": "Dugtrio (Head One)",
              "c": "Too late, flower. The door's already open."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "I would like to dramatically disagree — but I'm afraid he's right."
            },
            {
              "t": "p",
              "c": "Far to the north, something metallic caught the moonlight. Moving fast. Moving low. Getting closer."
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        },
        "full": {
          "scene": "High above the northern cave face, a lone Metang conducts a routine structural inspection — and discovers a crack that is anything but routine.",
          "paragraphs": [
            {
              "t": "a",
              "c": "[Scene opens on the sheer rock face of the northern caves, lit cold blue by a three-quarter moon. A Metang hovers six feet from the wall, a yellow construction warning marker clamped magnetically to the top of its head. It holds a clipboard in one claw. The clipboard is also held on by magnets. Metang is nothing if not consistent.]"
            },
            {
              "t": "p",
              "c": "Metang had been assigned to Section Seven of the northern cave perimeter as a structural assessor for Verdant Valley's entirely voluntary, almost entirely ignored Safety and Infrastructure Initiative. Most evenings this meant floating along the rock face, noting minor erosion, and returning home to file a report that no one would read until something fell on someone important. It was, Metang had decided long ago, a perfectly dignified profession."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "Section Seven. Upper face. Nominal surface integrity. Minor calcium deposit buildup at — CLUNK."
            },
            {
              "t": "a",
              "c": "[A fist-sized chunk of ceiling breaks away and drops squarely into Metang's outstretched claw. A beat. Metang looks at the chunk. Looks at the ceiling. Looks at the clipboard. Writes something down.]"
            },
            {
              "t": "p",
              "c": "The crack was not minor. It ran nearly four feet along the junction of wall and ceiling, spiderwebbing downward in three distinct branches, all converging toward the cave floor with the focused intention of something that had been stressed from below. Metang had seen earthquake damage, water erosion, and one memorable incident involving a Rhydon with a grudge. This was none of those things. This was tunneling. Recent. Deliberate."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "...That is not in my report."
            },
            {
              "t": "a",
              "c": "[Metang presses one flat steel claw against the crack and closes its eyes — or what passes for eyes. The vibrations travel up through the metal like a second language. Rhythmic. Repetitive. Getting closer.]"
            },
            {
              "t": "p",
              "c": "Inside the cave, Charizard was having what could generously be described as a complicated evening. The floor fracture had grown another six inches. The baby Pokémon — who had been sleeping in blissful ignorance forty minutes ago — were now comprehensively awake, comprehensively alarmed, and, in the case of one baby Snorlax, comprehensively sitting on a baby Jigglypuff."
            },
            {
              "t": "q",
              "speaker": "Charizard",
              "c": "Everything is fine. I need everyone to be calm. I am extremely calm. Look at me. I am the picture of — would someone please move the Snorlax."
            },
            {
              "t": "p",
              "c": "Nobody moved the Snorlax. The Jigglypuff made a sound like a squeeze toy having an existential crisis. Charizard, who had not asked to be here, had not asked to care about any of this, and was absolutely not going to admit that the sight of a crying Larvitar clinging to its tail had produced a feeling suspiciously close to tenderness — Charizard held it together. Barely."
            },
            {
              "t": "a",
              "c": "[From directly above, Metang hears the babies. It pauses its survey. The vibrations from below are now strong enough to feel without touching the wall. A decision is being made, silently, the way structural engineers make decisions — by calculating load, stress, failure points, and the specific expression on Charizard's face that it cannot yet see but somehow already knows is happening.]"
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "Unauthorized excavation. Active. Probable point of breach — south tunnel junction. Estimated time to surface fracture at current rate..."
            },
            {
              "t": "a",
              "c": "[Metang checks the clipboard. Then the crack. Then the clipboard again.]"
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "...Eight minutes. Possibly seven."
            },
            {
              "t": "p",
              "c": "Metang knocked three times on the cave wall — firm, official, the knock of someone who genuinely believed in process even when process had been catastrophically abandoned by everyone around them. CLANG. CLANG. CLANG. The digging paused for exactly two seconds. Then accelerated."
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "They are not going to file a permit."
            },
            {
              "t": "a",
              "c": "[Outside, at the mouth of the tunnel Dugtrio has already completed, Venusaur and Mismagius face the three-headed smirk of Team Rocket's finest underground operatives. The tunnel entrance yawns open behind them — wide enough. Tall enough. Ready.]"
            },
            {
              "t": "q",
              "speaker": "Dugtrio (Head One)",
              "c": "Hate to break it to you, flower pot, but the door's already open. All we needed was for you to be out here arguing about it while the real work got done."
            },
            {
              "t": "q",
              "speaker": "Dugtrio (Head Two)",
              "c": "Classic misdirection."
            },
            {
              "t": "q",
              "speaker": "Dugtrio (Head Three)",
              "c": "I mean, technically we were also arguing about it underground, but the point stands."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "I want to object to this outcome on principle. Unfortunately the principle in question is 'we were distracted,' and I was one of the people being distracted, so I'll simply observe that this is dreadful and let the moment speak for itself."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "We are NOT letting this moment speak for itself. We are DOING something. As soon as I figure out what."
            },
            {
              "t": "p",
              "c": "To the north, just beyond the ridge, something moved through the dark. Low. Fast. The moonlight caught a metallic glint — a silhouette that did not belong to any natural thing in Verdant Valley. It was still far away. But it was not slowing down."
            },
            {
              "t": "a",
              "c": "[Back at the cave wall, Metang makes a decision that is not in any inspection manual. It tucks the clipboard under one claw, faces the cracked stone, and raises the other claw — fingers spread, Guard Press activating with a low steel hum.]"
            },
            {
              "t": "q",
              "speaker": "Metang",
              "c": "...This is going to be a very long footnote."
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        }
      },
      {
        "id": 5,
        "slug": "blaze-of-glory-or-something-like-it",
        "title": "Blaze of Glory (Or Something Like It)",
        "cards": [
          {
            "name": "ソウブレイズ (Ceruledge) 109/106 AR",
            "set": "SV8",
            "artist": "Rond",
            "emoji": "⚔️",
            "image": "/images/cards/nufareizu.jpg"
          }
        ],
        "status": "live",
        "junior": {
          "scene": "The northern cave entrance — Genesect looms on the ridge, and a new warrior steps out of the shadows.",
          "paragraphs": [
            {
              "t": "p",
              "c": "The tunnel mouth glowed a horrible orange. Rocks were falling. Baby Pokémon were crying. And Genesect was getting VERY close."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"We are NOT ready for this.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"I would like to formally state that this is not my fault.\""
            },
            {
              "t": "a",
              "c": "CRACK. BOOM. A wall of the cave shattered outward. Rocks flew everywhere. Everyone ducked."
            },
            {
              "t": "p",
              "c": "And then — out of the dust and dark — came something nobody expected. A tall, armored figure with blue ghost-fire on its shoulders and two blazing swords at its sides. It moved slowly. Dramatically. Like it had been practicing."
            },
            {
              "t": "a",
              "c": "WHOOOOSH. The ghost-fire flared. The swords crossed. The dust swirled around it like it had ordered the dust on purpose."
            },
            {
              "t": "q",
              "speaker": "Ceruledge",
              "c": "\"I was in the area.\""
            },
            {
              "t": "p",
              "c": "Nobody knew who this was. Ceruledge did not explain further. Ceruledge simply turned toward Genesect on the ridge and pointed one glowing blade at the horizon."
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #1",
              "c": "\"Who IS that?!\""
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #2",
              "c": "\"No idea.\""
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #3",
              "c": "\"I think I've seen them at the sandwich shop.\""
            },
            {
              "t": "a",
              "c": "Ceruledge used Blaze Curse. A pulse of eerie flame rippled out across the tunnel. All of Dugtrio's Team Rocket gear fizzled and went dark. Every gadget. Every gizmo. Every tiny Rocket badge. GONE."
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #1",
              "c": "\"That was our equipment!\""
            },
            {
              "t": "q",
              "speaker": "Ceruledge",
              "c": "\"Yes.\""
            },
            {
              "t": "p",
              "c": "Inside the cave, Metang was still holding the wall. Charizard was still calming the babies. And now Ceruledge stood between Verdant Valley and Genesect's next move — swords crossed, ghost-fire blazing, completely unbothered."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"I feel like we should ask for their name at some point.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Give it a minute.\""
            },
            {
              "t": "p",
              "c": "On the ridge, Genesect's cannon began to charge. A deep red glow. A horrible hum. It was aiming straight at the cave entrance."
            },
            {
              "t": "a",
              "c": "Ceruledge did not flinch. Not even a little."
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        },
        "full": {
          "scene": "The northern cave entrance — the ground is cracked, Genesect stands on the ridge above, and an unexpected armored figure emerges from the chaos.",
          "paragraphs": [
            {
              "t": "p",
              "c": "There is a particular kind of silence that falls right before everything goes wrong. Venusaur had learned to recognize it. It smelled like ozone and bad decisions."
            },
            {
              "t": "a",
              "c": "[Scene opens on the northern cave entrance. Rubble skitters across the path. The tunnel mouth breathes warm, suspicious air. Above, on the ridge, Genesect's silhouette cuts against a bruised twilight sky, cannon arm raised. Inside the cave, faint sounds — Metang straining, babies whimpering, Charizard's low, soothing rumble.]"
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Right. So. We have a tunnel full of Rocket agents, a structural inspector holding up a wall with his bare hands, a dragon babysitting, and a mechanical monster on the ridge. Is that — is that the full picture? Anyone?\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"You forgot the part where I am personally having a terrible evening.\""
            },
            {
              "t": "p",
              "c": "Dugtrio had retreated three feet into the tunnel and was engaged in a hushed, furious argument between its three heads about what to do now that the ceiling was structurally compromised and their mission contact had stopped responding. Standard operations, really."
            },
            {
              "t": "a",
              "c": "Then the wall beside the tunnel mouth exploded."
            },
            {
              "t": "a",
              "c": "CRACK. A fracture line shot upward like a lightning bolt drawn by someone in a hurry. Rocks the size of small carriages tumbled loose. Venusaur threw up a Vine Whip to deflect the worst of it. Mismagius went incorporeal as debris passed through her. Both of them landed in a crouch, coughing, staring at the new gap in the rock face."
            },
            {
              "t": "p",
              "c": "From the dust emerged Ceruledge."
            },
            {
              "t": "p",
              "c": "Tall. Armored in deep navy and violet, every edge catching the last of the dying light. Ghost-fire burned blue on its shoulders — not frantically, not wildly, but with the focused calm of something that has decided. Twin blades at its sides, curved and luminous, trailing pale flame. It moved as though the dramatic entrance had been scheduled."
            },
            {
              "t": "q",
              "speaker": "Ceruledge",
              "c": "\"I was in the area.\""
            },
            {
              "t": "p",
              "c": "Venusaur stared. Mismagius stared. Even the Dugtrio, all three heads, stared."
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"...You were in the area. Of the collapsing cave.\""
            },
            {
              "t": "q",
              "speaker": "Ceruledge",
              "c": "\"The valley looked like it needed someone.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"It did. Desperately. And yet I feel like I need more context than that.\""
            },
            {
              "t": "p",
              "c": "Ceruledge did not provide more context. Ceruledge turned, measured the ridge above them with a long, unhurried look, and brought both blades together in a slow, deliberate cross."
            },
            {
              "t": "a",
              "c": "Blaze Curse. It came out of Ceruledge like an exhale — a pulse of ancient, cursed fire rolling low across the ground, seeking out every piece of special equipment at the tunnel mouth. Dugtrio's comm devices. The portable drill the Rockets had left behind. The energy-boosted digging implements they'd been so proud of."
            },
            {
              "t": "a",
              "c": "All of it — fizzled. Went dark. Dissolved into thin, smoking nothing."
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #1",
              "c": "\"That was — that took months to requisition.\""
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #2",
              "c": "\"Giovanni is going to be so upset.\""
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #3",
              "c": "\"I feel like now is a good time to reconsider our life choices.\""
            },
            {
              "t": "q",
              "speaker": "Dugtrio Head #1 and #2",
              "c": "\"Not now!\""
            },
            {
              "t": "p",
              "c": "Inside the cave, Charizard felt the tremor that wasn't a tremor — that particular stillness that means something outside just changed. She kept her voice steady for the babies. She kept her flame low and warm. But her eyes moved to the cave entrance, and something in her chest unknotted, just slightly, in a way she would absolutely never acknowledge."
            },
            {
              "t": "p",
              "c": "Metang, still braced against the cracked wall, registered the drop in seismic irregularity from the tunnel side. Filed it. Did not stop pressing. A win on one front did not mean the structural situation had improved. The structural situation had not improved. Metang was painfully aware of this."
            },
            {
              "t": "p",
              "c": "On the ridge, Genesect's cannon arm rotated downward, calibrating. The red glow at its core deepened. It had run its calculations. The cave entrance was the soft point. The cave entrance was the target."
            },
            {
              "t": "a",
              "c": "Ceruledge watched it happen. Watched the light gather. Watched the aim settle. And stood in front of the entrance anyway — blades up, ghost-fire steady, not a single armored inch of hesitation."
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"Are they — are they going to take that hit?\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"It appears so.\""
            },
            {
              "t": "q",
              "speaker": "Venusaur",
              "c": "\"That is either the bravest thing I've ever seen or the most reckless.\""
            },
            {
              "t": "q",
              "speaker": "Mismagius",
              "c": "\"In my experience, those are rarely different things.\""
            },
            {
              "t": "p",
              "c": "Mismagius drifted forward to flank. Venusaur, muttering something uncharitable under his breath, took the other side. Neither of them had agreed to this. Neither of them walked away."
            },
            {
              "t": "p",
              "c": "Genesect fired."
            },
            {
              "t": "end",
              "c": "To be continued..."
            }
          ]
        }
      }
    ]
  },
  {
    "id": "oceans-deep",
    "title": "Ocean's Deep",
    "tagline": "What sinks, must surface.",
    "genre": "Mystery • Thriller",
    "type": "Water",
    "color": "#3B82F6",
    "accent": "#93C5FD",
    "bg": "linear-gradient(135deg, #1E3A8A 0%, #1E40AF 50%, #0C1445 100%)",
    "desc": "A missing Lapras. A suspicious Gyarados. A detective Slowking who's way smarter than everyone thinks. Dive into the underwater mystery that has the whole reef talking.",
    "status": "Coming Soon",
    "epCount": 0,
    "episodes": []
  },
  {
    "id": "grass-is-greener",
    "title": "Grass Is Greener",
    "tagline": "The comedy that grows on you.",
    "genre": "Comedy • Slice of Life",
    "type": "Grass",
    "color": "#22C55E",
    "accent": "#86EFAC",
    "bg": "linear-gradient(135deg, #166534 0%, #15803D 50%, #052E16 100%)",
    "desc": "Bulbasaur just wanted a quiet garden. Then Oddish moved in next door. Then Sunflora started a podcast. Welcome to the funniest meadow in the Pokemon world.",
    "status": "Coming Soon",
    "epCount": 0,
    "episodes": []
  },
  {
    "id": "thunderstruck",
    "title": "Thunderstruck",
    "tagline": "When the storm hits, who will you become?",
    "genre": "Action • Coming of Age",
    "type": "Electric",
    "color": "#EAB308",
    "accent": "#FDE68A",
    "bg": "linear-gradient(135deg, #854D0E 0%, #A16207 50%, #422006 100%)",
    "desc": "A young Pichu trying to evolve, a legendary Raikou who refuses to teach, and a storm that's about to change everything.",
    "status": "Coming Soon",
    "epCount": 0,
    "episodes": []
  },
  {
    "id": "shadow-protocol",
    "title": "Shadow Protocol",
    "tagline": "Trust no one. Especially the ghost types.",
    "genre": "Espionage • Psychological Thriller",
    "type": "Dark",
    "color": "#A855F7",
    "accent": "#D8B4FE",
    "bg": "linear-gradient(135deg, #581C87 0%, #6B21A8 50%, #2E1065 100%)",
    "desc": "Gengar is running a spy ring. Absol knows too much. And someone in the shadows is pulling all the strings. A psychological thriller where nobody is innocent.",
    "status": "Coming Soon",
    "epCount": 0,
    "episodes": []
  },
  {
    "id": "iron-will",
    "title": "Iron Will",
    "tagline": "Forged in fire. Tested by fate.",
    "genre": "Epic • War Drama",
    "type": "Steel",
    "color": "#94A3B8",
    "accent": "#CBD5E1",
    "bg": "linear-gradient(135deg, #334155 0%, #475569 50%, #1E293B 100%)",
    "desc": "An ancient conflict. A reluctant Lucario. A kingdom on the edge of collapse. The steel-type epic that will test everything you believe about honor and sacrifice.",
    "status": "Coming Soon",
    "epCount": 0,
    "episodes": []
  }
];

export const SHOP: ShopProduct[] = [
  {
    "id": 1,
    "icon": "🔥",
    "name": "Charizard V (SAR)",
    "desc": "The card that started Episode 1",
    "price": "~$45",
    "cat": "Featured",
    "url": "#"
  },
  {
    "id": 2,
    "icon": "📦",
    "name": "VSTAR Universe Booster Box",
    "desc": "Pull your own SAR cards. 10 packs.",
    "price": "~$85",
    "cat": "Booster",
    "url": "#"
  },
  {
    "id": 3,
    "icon": "🛡️",
    "name": "Ultra Pro Sleeves (100ct)",
    "desc": "Matte sleeves to protect your pulls.",
    "price": "~$9",
    "cat": "Gear",
    "url": "#"
  },
  {
    "id": 4,
    "icon": "📒",
    "name": "9-Pocket Pro Binder",
    "desc": "Side-loading premium card display.",
    "price": "~$25",
    "cat": "Gear",
    "url": "#"
  },
  {
    "id": 5,
    "icon": "🎴",
    "name": "Pokemon 151 Bundle",
    "desc": "6 booster packs from the 151 set.",
    "price": "~$35",
    "cat": "Booster",
    "url": "#"
  },
  {
    "id": 6,
    "icon": "🔍",
    "name": "LED Magnifying Loupe",
    "desc": "Inspect card condition. 60x zoom.",
    "price": "~$12",
    "cat": "Gear",
    "url": "#"
  }
];

export const SHOP_CATEGORIES = ["All","Featured","Booster","Gear"] as const;
export const BROWSE_TYPES = ["All","Fire","Water","Grass","Electric","Dark","Steel"] as const;

export function getSeriesBySlug(slug: string): Series | undefined {
  return SERIES.find((s) => s.id === slug);
}

export function getEpisodeBySlugs(
  seriesSlug: string,
  episodeSlug: string
): { series: Series; episode: (typeof SERIES)[0]["episodes"][0] } | undefined {
  const series = getSeriesBySlug(seriesSlug);
  if (!series) return undefined;
  const episode = series.episodes.find((e) => e.slug === episodeSlug);
  if (!episode) return undefined;
  return { series, episode };
}

export function getAllEpisodePaths(): {
  seriesSlug: string;
  episodeSlug: string;
}[] {
  const paths: { seriesSlug: string; episodeSlug: string }[] = [];
  for (const series of SERIES) {
    for (const ep of series.episodes) {
      if (ep.status === "live") {
        paths.push({ seriesSlug: series.id, episodeSlug: ep.slug });
      }
    }
  }
  return paths;
}
