import type { Series, ShopProduct } from "./types";

export const SERIES: Series[] = [
  {
    id: "flames-of-our-lives",
    title: "Flames of Our Lives",
    tagline: "Love burns. So does Charizard.",
    genre: "Soap Opera • Drama • Comedy",
    type: "Fire",
    color: "#E8651A",
    accent: "#FFB347",
    bg: "linear-gradient(135deg, #E8651A 0%, #C41E3A 50%, #8B1A1A 100%)",
    desc: "The most dramatic saga in Verdant Valley. Fire-types with too many feelings, secrets that burn hotter than any Flamethrower, and a Venusaur who just wants answers.",
    status: "Airing",
    epCount: 3,
    episodes: [
      {
        id: 1,
        slug: "the-nap-that-changed-everything",
        title: "The Nap That Changed Everything",
        cards: [
          { name: "Charizard V (SAR)", set: "VSTAR Universe", artist: "Oswaldo KATO", emoji: "\u{1F525}", affiliateUrl: "#" },
        ],
        products: [
          { name: "VSTAR Universe Booster Box", url: "#", price: "~$85", tag: "Booster", emoji: "\u{1F4E6}" },
          { name: "Ultra Pro Sleeves (100ct)", url: "#", price: "~$9", tag: "Sleeves", emoji: "\u{1F6E1}\uFE0F" },
          { name: "9-Pocket Pro Binder", url: "#", price: "~$25", tag: "Binder", emoji: "\u{1F4D2}" },
        ],
        status: "live",
        junior: {
          scene: "A sunny meadow in Verdant Valley",
          paragraphs: [
            { t: "p", c: "Charizard was the biggest, strongest Pok\u00e9mon in Verdant Valley. He could fly super fast. He could breathe fire that was SO hot. He was amazing." },
            { t: "p", c: "But right now? He was taking a nap." },
            { t: "p", c: "Not just any nap. The BIGGEST nap. He was curled up in the grass like a giant orange cat, snoring so loud that the leaves were falling off the trees. His tail flame went flicker... flicker... flicker..." },
            { t: "p", c: "Venusaur was watching from behind a hill. Venusaur was big and green and covered in flowers, and right now he was very, VERY grumpy." },
            { t: "q", speaker: "Venusaur", c: "\"Are you KIDDING me? He burned down half the meadow last week! And now he's sleeping here like nothing happened!\"" },
            { t: "p", c: "Everyone in the valley thought Charizard was selfish. He never helped with anything. He never came to the valley meetings. He just flew around and napped and sometimes accidentally set things on fire." },
            { t: "p", c: "But here's the secret. The BIG secret." },
            { t: "p", c: "Charizard wasn't being lazy. He was EXHAUSTED." },
            { t: "p", c: "Every single night, when everyone was asleep, Charizard flew to the caves on the north side of the valley. A big storm had knocked down the trees near the caves, and all the baby Pok\u00e9mon who lived there were cold. Really, really cold." },
            { t: "p", c: "So Charizard used his fire breath \u2014 very carefully, very gently \u2014 to keep the caves warm all night long. He kept the little Charmanders warm. He kept the shivering Eevees warm. He even kept a very grumpy Snorlax warm, even though Snorlax said he was \"fine\" (he was NOT fine)." },
            { t: "p", c: "But Charizard never told anyone. He was too proud. He didn't want anyone to think he was... nice." },
            { t: "a", c: "\u2014 a leaf floats gently across the meadow \u2014" },
            { t: "p", c: "Back on the hill, Venusaur squinted his eyes. He noticed something weird. The burn marks on Charizard's claws didn't look like accident burns. They looked like WORK burns. Like he'd been doing something careful and hard, over and over again." },
            { t: "q", speaker: "Venusaur", c: "\"Hmm. Something's going on with that big lizard... and I'm going to find out WHAT.\"" },
            { t: "end", c: "To be continued..." },
          ],
        },
        full: {
          scene: "A sunlit clearing in Verdant Valley",
          paragraphs: [
            { t: "p", c: "Charizard \u2014 once the most feared, most powerful, most dramatic fire-breather in all of Verdant Valley \u2014 was\u2026 taking a nap." },
            { t: "p", c: "Not just any nap. A legendary nap. Curled up like a giant orange cat, tail flame flickering lazily, snoring loud enough to shake the leaves off the trees. Some of those trees? Already a little burnt. Nobody talks about that." },
            { t: "p", c: "In the background, Venusaur watched from behind a hill, squinting." },
            { t: "q", speaker: "Venusaur", c: "\"Unbelievable. He burns down half the meadow LAST Tuesday, doesn't apologize, and now he's sleeping like a baby in the SAME meadow. The audacity.\"" },
            { t: "p", c: "But here's the thing nobody knew \u2014 Charizard wasn't just being lazy. He was exhausted." },
            { t: "p", c: "For weeks, he'd been secretly flying across the valley every night, using his Heat Blast to keep the northern caves warm for the baby Pok\u00e9mon who'd lost their homes after the big storm. The little Charmanders, the shivering Eevees, even a very grumpy Snorlax who refused to admit he was cold." },
            { t: "p", c: "He never told anyone. Too proud. Too stubborn. Too\u2026 Charizard." },
            { t: "p", c: "So while the valley gossiped about the \"selfish dragon,\" Charizard just curled up tighter, let the sun warm his wings, and dreamed of a world where nobody needed saving anymore." },
            { t: "a", c: "\u2014 a leaf blows gently across the clearing \u2014" },
            { t: "p", c: "Venusaur narrowed his eyes. Something didn't add up. The scorch marks on Charizard's claws weren't from recklessness \u2014 they were from work. Long, careful, exhausting work." },
            { t: "q", speaker: "Venusaur", c: "\"Something's going on with that oversized lizard\u2026 and I'm going to find out what.\"" },
            { t: "end", c: "To be continued\u2026" },
          ],
        },
      },
      {
        id: 2,
        slug: "the-witch-who-knew-too-much",
        title: "The Witch Who Knew Too Much",
        cards: [
          { name: "Mismagius ex", set: "M2 (036/080 RR)", artist: "5ban Graphics", emoji: "\u{1F47B}", affiliateUrl: "#" },
          { name: "Genesect V", set: "VSTAR Universe (102/172 RR)", artist: "PLANETA Tsuji", emoji: "\u{1F916}", affiliateUrl: "#" },
        ],
        products: [
          { name: "Pok\u00e9mon 151 Bundle (6 packs)", url: "#", price: "~$35", tag: "Booster", emoji: "\u{1F3B4}" },
          { name: "Ultra Pro Sleeves (100ct)", url: "#", price: "~$9", tag: "Sleeves", emoji: "\u{1F6E1}\uFE0F" },
          { name: "LED Magnifying Loupe", url: "#", price: "~$12", tag: "Gear", emoji: "\u{1F50D}" },
        ],
        status: "live",
        junior: {
          scene: "The edge of the valley, nighttime. Fog everywhere.",
          paragraphs: [
            { t: "p", c: "Venusaur couldn't sleep. He kept thinking about Charizard and those weird burn marks on his claws." },
            { t: "p", c: "So tonight, he decided to follow Charizard. Like a detective! A really big, really slow, really loud detective." },
            { t: "p", c: "The sun went down. The stars came out. And sure enough \u2014 Charizard woke up, stretched his wings, and flew north." },
            { t: "p", c: "Venusaur tried to sneak through the forest after him. But sneaking is hard when you weigh as much as a car." },
            { t: "p", c: "CRUNCH. SNAP. CRUNCH." },
            { t: "q", speaker: "???", c: "\"You know, for a spy, you're really, REALLY bad at this.\"" },
            { t: "p", c: "Venusaur froze. That voice came from... everywhere? He looked left. He looked right. He looked up." },
            { t: "p", c: "And there she was." },
            { t: "a", c: "\u2014 purple mist swirls and sparkles fill the air \u2014" },
            { t: "p", c: "Mismagius floated down from the treetops, covered in sparkles and glowing purple light. She was a Ghost-type who'd lived in the valley forever. Nobody knew where she came from. She just... showed up wherever something interesting was happening." },
            { t: "p", c: "Some Pok\u00e9mon called her the Witch. She preferred \"Observer.\"" },
            { t: "q", speaker: "Mismagius", c: "\"You're following the big dragon, aren't you?\"" },
            { t: "q", speaker: "Venusaur", c: "\"I'm INVESTIGATING. That's different.\"" },
            { t: "q", speaker: "Mismagius", c: "\"Sure, sure. Very professional. Very sneaky. Not at all like a Tauros crashing through a gift shop.\"" },
            { t: "p", c: "Venusaur's face got hot. His flower started blooming. That always happened when he was embarrassed." },
            { t: "q", speaker: "Venusaur", c: "\"Do you know what Charizard is doing every night?\"" },
            { t: "p", c: "Mismagius stopped smiling. Her sparkles changed from pink to dark purple. She floated closer." },
            { t: "q", speaker: "Mismagius", c: "\"I know EVERYTHING that happens in this valley at night. I know Charizard flies to the northern caves to keep the baby Pok\u00e9mon warm. But that's not the scary part.\"" },
            { t: "q", speaker: "Venusaur", c: "\"There's a SCARY PART?\"" },
            { t: "q", speaker: "Mismagius", c: "\"Something new has come to the valley. Something made of metal. It has a cannon on its back. It doesn't eat. It doesn't sleep. It just flies around scanning everything. And it's heading straight for those caves.\"" },
            { t: "a", c: "\u2014 SCREEEEECH! A metallic sound echoes from the mountains \u2014" },
            { t: "p", c: "They both looked up. A streak of purple and silver light shot across the sky like a rocket. It wasn't a bird. It wasn't a Pok\u00e9mon they'd ever seen. It moved like a machine \u2014 fast, sharp, and scary." },
            { t: "p", c: "Genesect. A robotic Pok\u00e9mon with a giant cannon on its back, blasting through the sky straight toward the northern caves." },
            { t: "p", c: "Straight toward Charizard. Straight toward the babies." },
            { t: "q", speaker: "Venusaur", c: "\"We have to warn Charizard! NOW!\"" },
            { t: "q", speaker: "Mismagius", c: "\"WE? Oh no no no. I'm a ghost. I float and I watch. I don't DO running.\"" },
            { t: "q", speaker: "Venusaur", c: "\"Mismagius. Please.\"" },
            { t: "p", c: "She looked at him for a long moment. Then she sighed \u2014 a sigh that made all the flowers around them shiver." },
            { t: "q", speaker: "Mismagius", c: "\"Fine. But I'm floating the whole way. And if anything bad happens, I'm blaming you.\"" },
            { t: "p", c: "And so the grumpiest Pok\u00e9mon in the valley and the spookiest Pok\u00e9mon in the valley started running (and floating) north as fast as they could." },
            { t: "p", c: "Behind them, the valley slept peacefully." },
            { t: "p", c: "Ahead of them, Charizard had no idea what was coming." },
            { t: "p", c: "And above them, Genesect's cannon glowed in the dark." },
            { t: "end", c: "To be continued..." },
          ],
        },
        full: {
          scene: "The edge of Verdant Valley, twilight. Fog rolling in.",
          paragraphs: [
            { t: "p", c: "Venusaur couldn't sleep." },
            { t: "p", c: "It had been three days since he'd noticed the scorch marks on Charizard's claws. Three days of watching that overgrown fire hazard nap in the meadow like he didn't have a care in the world. Three days of knowing something was off and not being able to prove it." },
            { t: "p", c: "So tonight, Venusaur did something he'd never done in fourteen years of living in this valley. He followed someone." },
            { t: "p", c: "The moment the sun dipped below the ridge and the last Pidgey stopped chirping, Charizard stirred. Stretched his wings. Yawned a column of fire that nearly scorched a passing Butterfree \u2014 \"SORRY!\" \u2014 and launched into the sky heading north." },
            { t: "p", c: "Venusaur lumbered after him on the ground, sticking to the tree line, moving as quietly as a four-hundred-pound dinosaur plant possibly could. Which was not quietly at all." },
            { t: "q", speaker: "Mismagius", c: "\"You know, for a spy, you're absolutely terrible at this.\"" },
            { t: "p", c: "The voice came from everywhere and nowhere. It floated down like silk made of smoke, curling around his ears with a warmth that felt... wrong. Too warm. The kind of warm that makes you forget what you were doing." },
            { t: "a", c: "\u2014 the fog parts, and a swirl of purple mist takes shape \u2014" },
            { t: "p", c: "Mismagius descended from the canopy, trailing sparkles and pink crystal light like she was her own special effect. Her eyes \u2014 those impossible red eyes \u2014 locked onto Venusaur with the expression of someone who had been watching this whole situation unfold for weeks and was deeply entertained by it." },
            { t: "p", c: "Mismagius was the valley's oldest mystery. Nobody knew when she'd arrived. Nobody knew where she lived. She showed up at every major event \u2014 every argument, every breakup, every midnight scandal \u2014 and watched from the shadows with that little smile." },
            { t: "p", c: "Some Pok\u00e9mon called her the Oracle. Others called her the Witch. Snorlax once called her \"deeply unsettling,\" which was the most words Snorlax had used in a single sentence all year." },
            { t: "q", speaker: "Mismagius", c: "\"You're following the dragon.\"" },
            { t: "q", speaker: "Venusaur", c: "\"I'm investigating. There's a difference.\"" },
            { t: "q", speaker: "Mismagius", c: "\"Mmm. Of course. Very official. Very dignified. Very much stumbling through bushes at midnight like a confused Tauros.\"" },
            { t: "p", c: "Venusaur felt his face go hot. Which, for a Grass-type, meant his flower actually started to bloom a little. Embarrassing." },
            { t: "q", speaker: "Venusaur", c: "\"Do you know what he's doing? The night flights? The scorch marks?\"" },
            { t: "p", c: "Mismagius tilted her head. The sparkles around her shifted from pink to deep violet. When she spoke, her voice dropped to something almost serious." },
            { t: "q", speaker: "Mismagius", c: "\"I know everything that happens in this valley after dark, Venusaur. Everything. I know that Charizard flies north every single night. I know what he does when he gets there. And I know that you're not going to like the answer \u2014 not because it's bad, but because it's going to make you feel guilty for every rotten thing you've said about him.\"" },
            { t: "p", c: "She drifted closer. The air around her got colder. The sparkles died." },
            { t: "q", speaker: "Mismagius", c: "\"He's not just keeping them warm. He's guarding them. Something has been approaching the northern ridge for the past two weeks. Something none of us have ever seen before. Metal body. Red eyes. A cannon on its back. It doesn't eat. It doesn't sleep. It just... scans. Like it's searching for something.\"" },
            { t: "p", c: "Venusaur felt the vines on his back tighten involuntarily." },
            { t: "a", c: "\u2014 a distant metallic screech echoes from the northern mountains \u2014" },
            { t: "p", c: "Both of them turned toward the sound. Above the treeline, a streak of purple and silver light cut across the sky like a comet with a grudge. Fast. Precise. Nothing natural about it." },
            { t: "p", c: "Genesect had arrived in Verdant Valley. Not walking. Not flying in the way birds fly \u2014 no grace, no wind. It moved like a machine that had calculated the most efficient trajectory between two points and simply executed. The cannon on its back glowed a sickly violet, scanning the terrain below." },
            { t: "p", c: "It was heading straight for the northern caves. Straight for Charizard." },
            { t: "q", speaker: "Venusaur", c: "\"We have to warn him.\"" },
            { t: "q", speaker: "Mismagius", c: "\"We? Oh no no no. You have to warn him. I'm an observer. I observe. I comment. I occasionally make things sparkle. I do not do... running.\"" },
            { t: "q", speaker: "Venusaur", c: "\"Mismagius. Please.\"" },
            { t: "p", c: "She looked at him. Really looked at him \u2014 past the grumpy exterior and the judgmental squinting and the fourteen years of loudly complaining about Charizard at every community meeting." },
            { t: "q", speaker: "Mismagius", c: "\"...You actually care about him, don't you?\"" },
            { t: "p", c: "Venusaur said nothing. His flower bloomed a little more." },
            { t: "q", speaker: "Mismagius", c: "\"Fine. But I'm floating. And if I die, I'm haunting you specifically.\"" },
            { t: "q", speaker: "Venusaur", c: "\"You're already a ghost.\"" },
            { t: "q", speaker: "Mismagius", c: "\"Then I'll haunt you harder.\"" },
            { t: "p", c: "They moved north. Venusaur running \u2014 actually running \u2014 for the first time in years. Mismagius gliding beside him, trailing purple light and looking like the most reluctant hero in the history of Verdant Valley." },
            { t: "p", c: "Behind them, the valley slept peacefully. Ahead of them, a dragon who didn't know he needed saving was about to meet something that didn't know it needed stopping." },
            { t: "p", c: "And above them all, Genesect's cannon hummed." },
            { t: "end", c: "To be continued\u2026" },
          ],
        },
      },
      {
        id: 3,
        slug: "the-ground-beneath-their-feet",
        title: "The Ground Beneath Their Feet",
        cards: [
          { name: "Team Rocket's Dugtrio", set: "M2a (083/193)", artist: "KEIICHIRO ITO", emoji: "\u{1F4A5}", affiliateUrl: "#" },
        ],
        products: [
          { name: "M2a Space-Time Smackdown Box", url: "#", price: "~$45", tag: "Booster", emoji: "\u{1F30C}" },
          { name: "KMC Perfect Fit Inner Sleeves (100ct)", url: "#", price: "~$6", tag: "Sleeves", emoji: "\u{1F6E1}\uFE0F" },
          { name: "BCW Card Storage Box (3200ct)", url: "#", price: "~$18", tag: "Gear", emoji: "\u{1F4E6}" },
        ],
        status: "live",
        junior: {
          scene: "The northern caves, night. The ground is shaking.",
          paragraphs: [
            { t: "p", c: "Venusaur and Mismagius ran (and floated) as fast as they could toward the northern caves. They could see Charizard's fire glowing in the distance." },
            { t: "p", c: "But something was wrong. The ground was shaking." },
            { t: "p", c: "Not a little shake. A BIG shake. The kind of shake where the trees wiggle and the rocks bounce and Venusaur almost fell on his face THREE times." },
            { t: "q", speaker: "Venusaur", c: "\"What is HAPPENING?!\"" },
            { t: "q", speaker: "Mismagius", c: "\"The ground is breaking apart! Something is tunneling underneath us!\"" },
            { t: "a", c: "\u2014 CRACK! RUMBLE! CRASH! The cave entrance splits in two \u2014" },
            { t: "p", c: "They burst through the trees and saw the caves. And it was BAD." },
            { t: "p", c: "Genesect was flying above the caves, firing laser blasts from its cannon. BOOM! BOOM! Rocks exploded everywhere. The baby Pok\u00e9mon inside were crying." },
            { t: "p", c: "And from BELOW the caves, three brown heads popped out of the ground. Dugtrio! But this wasn't a normal Dugtrio. It had mean, angry eyes. And on the rocks near the tunnel entrance, someone had painted a big red letter R." },
            { t: "p", c: "Team Rocket." },
            { t: "p", c: "Dugtrio was digging tunnels UNDER the caves, making the floor collapse! Genesect attacked from above. Dugtrio destroyed from below. It was a trap!" },
            { t: "p", c: "Charizard was already fighting. He was blasting fire at Genesect, trying to keep it away from the cave entrance. But he was tired. So, SO tired. He'd been warming the caves all night, and now he had to fight too." },
            { t: "q", speaker: "Charizard", c: "\"Get... AWAY from them!\"" },
            { t: "p", c: "His fire blast hit Genesect, but Genesect barely flinched. Its metal body just glowed red for a second, and then it fired back. Charizard dodged, but just barely." },
            { t: "q", speaker: "Venusaur", c: "\"CHARIZARD! We're here! We came to help!\"" },
            { t: "p", c: "Charizard looked down and saw Venusaur and Mismagius. His eyes went wide. For a second, he looked like he might cry. But Charizards don't cry. They just... breathe fire a little harder." },
            { t: "p", c: "They made a plan in ten seconds flat. Charizard took the sky \u2014 fire blasts to keep Genesect busy. Venusaur sent his vines deep into the ground, wrapping around rocks and roots, holding the cave floor together like a giant green net. And Mismagius? She turned invisible and floated into Dugtrio's tunnels." },
            { t: "p", c: "Dugtrio saw glowing purple eyes in the darkness of its own tunnel. Then two eyes. Then TEN eyes. Mismagius made it look like an army of ghosts was coming straight at it." },
            { t: "q", speaker: "Dugtrio", c: "\"AHHHHH!\"" },
            { t: "p", c: "Dugtrio freaked out and tunneled away SO fast it left a dust cloud shaped like itself. Genesect, seeing its partner flee, fired one last shot and rocketed into the sky, disappearing in a flash of purple light." },
            { t: "p", c: "The caves were safe. The babies were safe. Venusaur's vines were holding everything together. Charizard landed hard, exhausted, and for the first time ever... he looked at Venusaur and said:" },
            { t: "q", speaker: "Charizard", c: "\"...Thanks.\"" },
            { t: "p", c: "Venusaur's flower bloomed so hard it almost exploded." },
            { t: "a", c: "\u2014 the dust settles and moonlight returns to the caves \u2014" },
            { t: "p", c: "But Mismagius wasn't smiling. She floated back from the tunnels holding something she'd found deep underground. A metal badge. Shiny. Cold. With a big red R stamped on it." },
            { t: "q", speaker: "Mismagius", c: "\"This wasn't just a random attack. Those two were sent here. By Team Rocket. And if they sent two... they'll send more.\"" },
            { t: "p", c: "Charizard, Venusaur, and Mismagius looked at each other. The babies were safe tonight. But what about tomorrow night? And the night after that?" },
            { t: "p", c: "Somewhere far away, in a building with no windows, a screen flickered. A grunt in a black uniform watched Dugtrio and Genesect retreat on a radar map. He picked up a phone." },
            { t: "q", speaker: "???", c: "\"Send the next team. The valley has more fight than we expected.\"" },
            { t: "end", c: "To be continued..." },
          ],
        },
        full: {
          scene: "The northern caves, deep night. The earth itself is trembling.",
          paragraphs: [
            { t: "p", c: "They heard the caves before they saw them." },
            { t: "p", c: "A low, grinding vibration rolled through the forest floor \u2014 not thunder, not wind, but something beneath. Something deliberate. The trees swayed without breeze. Pebbles danced on flat stones like water on a hot pan. Venusaur felt it in his roots, in the deep places where instinct lived." },
            { t: "q", speaker: "Venusaur", c: "\"The ground is wrong. Something is tunneling beneath us.\"" },
            { t: "q", speaker: "Mismagius", c: "\"Not something. Someone. And they've been at it for a while.\"" },
            { t: "p", c: "They broke through the tree line and the world opened into a nightmare." },
            { t: "a", c: "\u2014 an explosion of rock and light above the northern caves \u2014" },
            { t: "p", c: "Genesect hung in the air above the cave entrance like a malevolent star, its cannon cycling through violet charges and releasing them in precise, devastating arcs. Each blast struck the cliff face with surgical accuracy \u2014 not random destruction, but calculated demolition. It was taking the caves apart piece by piece." },
            { t: "p", c: "And below \u2014 below was worse." },
            { t: "p", c: "Three brown heads emerged from a fissure in the earth twenty meters from the cave mouth. Dugtrio. But not wild \u2014 Venusaur could see it immediately. The movements were too coordinated, too purposeful. This creature answered to someone. And carved into the rock wall beside the tunnel it had emerged from, fresh and unmistakable, was a symbol: a crimson R." },
            { t: "p", c: "Team Rocket. The name carried weight even here, even in a valley that had spent decades pretending the outside world couldn't touch it." },
            { t: "p", c: "Dugtrio worked in silence, boring through the substrate beneath the caves with mechanical efficiency, each tunnel weakening the foundation a little more. Genesect attacked from above. Dugtrio eroded from below. A pincer operation executed with the cold logic of machines and the cruelty of people who built them." },
            { t: "p", c: "And in the middle of it all, Charizard fought alone." },
            { t: "p", c: "He was magnificent and he was failing. Fire Blast after Fire Blast lit up the night sky, driving Genesect back, buying seconds for the cave entrance. But Charizard had been warming those caves for hours before the attack began. His flame was already low. His wings trembled on every upstroke. A blast from Genesect's cannon caught his left shoulder and he spiraled, caught himself, and climbed again \u2014 slower this time." },
            { t: "q", speaker: "Charizard", c: "\"Come on, you metal freak. COME ON.\"" },
            { t: "p", c: "Inside the caves, Venusaur could hear them \u2014 the babies. Charmanders crying. Eevees pressed against the back wall. That stubborn Snorlax, finally awake and terrified, trying to shield the smaller ones with his body. The floor beneath them cracking." },
            { t: "q", speaker: "Venusaur", c: "\"We need to move. NOW.\"" },
            { t: "p", c: "What happened next took eleven seconds. Venusaur had never moved that fast in his life and probably never would again." },
            { t: "p", c: "He charged. Four hundred pounds of Grass-type fury barreling toward the cave mouth. His vines \u2014 all of them, every tendril he had \u2014 shot into the ground like anchors, threading through rock and root and clay, weaving a lattice beneath the cave floor. It wouldn't hold forever. But it would hold long enough." },
            { t: "p", c: "Charizard saw Venusaur arrive and his eyes went wide. For one unguarded moment, the proud dragon looked like what he actually was \u2014 exhausted, overwhelmed, and unspeakably grateful that he wasn't alone anymore." },
            { t: "q", speaker: "Charizard", c: "\"Venusaur? What are you \u2014\"" },
            { t: "q", speaker: "Venusaur", c: "\"SHUT UP AND KEEP FLYING! I've got the ground!\"" },
            { t: "p", c: "Charizard shut up and kept flying. Overhead, his fire renewed \u2014 not because his energy had returned, but because something fiercer had taken the place of exhaustion. He wasn't fighting alone. That changed things." },
            { t: "p", c: "Mismagius, meanwhile, had already vanished." },
            { t: "p", c: "She phased through solid rock and descended into Dugtrio's tunnel network. In the absolute darkness sixty feet below the surface, she let herself become what Ghost-types truly are when they stop performing for an audience. Her form dissolved into pure spectral energy \u2014 eyes multiplying, voice splitting into layered harmonics, the temperature dropping so fast that frost crystallized on the tunnel walls." },
            { t: "p", c: "Dugtrio turned and saw the darkness behind it fill with light. Not warm light. The cold, violet, ancient light of something that existed before the concept of mercy was invented." },
            { t: "q", speaker: "Mismagius", c: "\"You are in my valley. You are beneath my ground. And I am the thing that lives in the dark down here.\"" },
            { t: "p", c: "Dugtrio fled. There was no other word for it. All three heads screamed in unison and the creature burrowed away so fast it left a vacuum in its wake, the tunnel collapsing behind it. Up above, Genesect registered its partner's retreat on whatever internal systems governed its tactical decisions. It fired one final volley \u2014 a parting shot that cracked the cliff face above the cave entrance \u2014 and rocketed skyward, disappearing into the clouds like a violet comet." },
            { t: "p", c: "Silence." },
            { t: "p", c: "Charizard landed hard at the cave mouth, wings folded, chest heaving. Venusaur's vines still held the ground together, roots trembling with the strain. Inside the caves, a Charmander peeked out from behind Snorlax's belly. Then an Eevee. Then another." },
            { t: "q", speaker: "Charizard", c: "\"...You came.\"" },
            { t: "q", speaker: "Venusaur", c: "\"Of course I came, you idiot. You think I'd let you have all the dramatic moments to yourself?\"" },
            { t: "p", c: "Charizard laughed. It was a rough, broken sound \u2014 half exhaustion, half something that had been wound too tight for too long finally releasing. His tail flame flickered. Venusaur's flower bloomed in the dark." },
            { t: "a", c: "\u2014 moonlight breaks through the dust, illuminating the ruined cave entrance \u2014" },
            { t: "p", c: "Mismagius emerged from the ground moments later, her usual sparkles dimmed, her expression something none of them had seen before. Serious. Genuinely, deeply serious." },
            { t: "p", c: "In her spectral grasp, she held a small metal object. A badge. Matte black with a crimson R embossed on its surface. It was warm to the touch and hummed faintly \u2014 a transmitter." },
            { t: "q", speaker: "Mismagius", c: "\"This wasn't a raid. It was a reconnaissance mission. They weren't trying to destroy the caves. They were testing defenses. Mapping the valley. And this \u2014\" she held up the badge, \"\u2014 has been broadcasting our location since the moment they arrived.\"" },
            { t: "p", c: "The three of them stood in the wreckage of the cave entrance, surrounded by sleeping babies and broken stone, and understood the same thing at the same time: tonight was not the end of something. It was the beginning." },
            { t: "p", c: "Somewhere beyond the mountains, in a facility that didn't appear on any map, a monitor displayed three thermal signatures clustered around the northern caves. A grunt in a black uniform picked up a secure line." },
            { t: "q", speaker: "???", c: "\"Dugtrio and Genesect have been repelled. But we have the data. The valley is defended, but not by much. Three hostiles. One fire, one grass, one ghost. Recommend escalating to Phase Two.\"" },
            { t: "p", c: "The line crackled. Then a voice \u2014 calm, measured, the kind of voice that had never needed to raise itself:" },
            { t: "q", speaker: "???", c: "\"Approved. Send the next unit. And this time, don't underestimate the dragon.\"" },
            { t: "end", c: "To be continued\u2026" },
          ],
        },
      },
    ],
  },
  {
    id: "oceans-deep",
    title: "Ocean's Deep",
    tagline: "What sinks, must surface.",
    genre: "Mystery • Thriller",
    type: "Water",
    color: "#3B82F6",
    accent: "#93C5FD",
    bg: "linear-gradient(135deg, #1E3A8A 0%, #1E40AF 50%, #0C1445 100%)",
    desc: "A missing Lapras. A suspicious Gyarados. A detective Slowking who's way smarter than everyone thinks. Dive into the underwater mystery that has the whole reef talking.",
    status: "Coming Soon",
    epCount: 0,
    episodes: [],
  },
  {
    id: "grass-is-greener",
    title: "Grass Is Greener",
    tagline: "The comedy that grows on you.",
    genre: "Comedy • Slice of Life",
    type: "Grass",
    color: "#22C55E",
    accent: "#86EFAC",
    bg: "linear-gradient(135deg, #166534 0%, #15803D 50%, #052E16 100%)",
    desc: "Bulbasaur just wanted a quiet garden. Then Oddish moved in next door. Then Sunflora started a podcast. Welcome to the funniest meadow in the Pokemon world.",
    status: "Coming Soon",
    epCount: 0,
    episodes: [],
  },
  {
    id: "thunderstruck",
    title: "Thunderstruck",
    tagline: "When the storm hits, who will you become?",
    genre: "Action • Coming of Age",
    type: "Electric",
    color: "#EAB308",
    accent: "#FDE68A",
    bg: "linear-gradient(135deg, #854D0E 0%, #A16207 50%, #422006 100%)",
    desc: "A young Pichu trying to evolve, a legendary Raikou who refuses to teach, and a storm that's about to change everything.",
    status: "Coming Soon",
    epCount: 0,
    episodes: [],
  },
  {
    id: "shadow-protocol",
    title: "Shadow Protocol",
    tagline: "Trust no one. Especially the ghost types.",
    genre: "Espionage • Psychological Thriller",
    type: "Dark",
    color: "#A855F7",
    accent: "#D8B4FE",
    bg: "linear-gradient(135deg, #581C87 0%, #6B21A8 50%, #2E1065 100%)",
    desc: "Gengar is running a spy ring. Absol knows too much. And someone in the shadows is pulling all the strings. A psychological thriller where nobody is innocent.",
    status: "Coming Soon",
    epCount: 0,
    episodes: [],
  },
  {
    id: "iron-will",
    title: "Iron Will",
    tagline: "Forged in fire. Tested by fate.",
    genre: "Epic • War Drama",
    type: "Steel",
    color: "#94A3B8",
    accent: "#CBD5E1",
    bg: "linear-gradient(135deg, #334155 0%, #475569 50%, #1E293B 100%)",
    desc: "An ancient conflict. A reluctant Lucario. A kingdom on the edge of collapse. The steel-type epic that will test everything you believe about honor and sacrifice.",
    status: "Coming Soon",
    epCount: 0,
    episodes: [],
  },
];


export const SHOP: ShopProduct[] = [
  {
    id: 1,
    icon: "\u{1F525}",
    name: "Charizard V (SAR)",
    desc: "The card that started Episode 1",
    price: "~$45",
    cat: "Featured",
  },
  {
    id: 2,
    icon: "\u{1F4E6}",
    name: "VSTAR Universe Booster Box",
    desc: "Pull your own SAR cards. 10 packs.",
    price: "~$85",
    cat: "Booster",
  },
  {
    id: 3,
    icon: "\u{1F6E1}\uFE0F",
    name: "Ultra Pro Sleeves (100ct)",
    desc: "Matte sleeves to protect your pulls.",
    price: "~$9",
    cat: "Gear",
  },
  {
    id: 4,
    icon: "\u{1F4D2}",
    name: "9-Pocket Pro Binder",
    desc: "Side-loading premium card display.",
    price: "~$25",
    cat: "Gear",
  },
  {
    id: 5,
    icon: "\u{1F3B4}",
    name: "Pokemon 151 Bundle",
    desc: "6 booster packs from the 151 set.",
    price: "~$35",
    cat: "Booster",
  },
  {
    id: 6,
    icon: "\u{1F50D}",
    name: "LED Magnifying Loupe",
    desc: "Inspect card condition. 60x zoom.",
    price: "~$12",
    cat: "Gear",
  },
];

export const SHOP_CATEGORIES = ["All", "Featured", "Booster", "Gear"] as const;
export const BROWSE_TYPES = [
  "All",
  "Fire",
  "Water",
  "Grass",
  "Electric",
  "Dark",
  "Steel",
] as const;

export function getSeriesBySlug(slug: string): Series | undefined {
  return SERIES.find((s) => s.id === slug);
}

export function getEpisodeBySlugs(
  seriesSlug: string,
  episodeSlug: string
): { series: Series; episode: (typeof SERIES)[0]["episodes"][0] } | undefined {
  const series = getSeriesBySlug(seriesSlug);
  if (!series) return undefined;
  const episode = series.episodes.find((e) => e.slug === episodeSlug);
  if (!episode) return undefined;
  return { series, episode };
}

export function getAllEpisodePaths(): {
  seriesSlug: string;
  episodeSlug: string;
}[] {
  const paths: { seriesSlug: string; episodeSlug: string }[] = [];
  for (const series of SERIES) {
    for (const ep of series.episodes) {
      if (ep.status === "live") {
        paths.push({ seriesSlug: series.id, episodeSlug: ep.slug });
      }
    }
  }
  return paths;
}
