/**
 * Pre-build script: reads series.json, shop.json, and episode JSON files
 * from clients/pokemon-fables/ and generates src/lib/data.ts.
 *
 * Reads episodes from per-series directories:
 *   clients/pokemon-fables/series/{series-id}/episodes/episode-*.json
 *
 * Run before `next build` via the "prebuild" npm script.
 *
 * Usage: node scripts/build-data.js
 */

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Hard-coded to pokemon-fables for now (only client)
const CLIENT = "pokemon-fables";
const clientDir = join(ROOT, "clients", CLIENT);
const outFile = join(ROOT, "src", "lib", "data.ts");

// Read series metadata
const series = JSON.parse(
  readFileSync(join(clientDir, "series.json"), "utf-8")
);

// Read shop data
const shop = JSON.parse(readFileSync(join(clientDir, "shop.json"), "utf-8"));

// Read episodes from per-series directories
let totalEpisodes = 0;

const seriesWithEpisodes = series.map((s) => {
  const seriesEpisodesDir = join(clientDir, "series", s.id, "episodes");

  if (!existsSync(seriesEpisodesDir)) {
    return { ...s, epCount: 0, episodes: [] };
  }

  const episodeFiles = readdirSync(seriesEpisodesDir)
    .filter((f) => f.startsWith("episode-") && f.endsWith(".json"))
    .sort((a, b) => {
      const numA = parseInt(a.match(/episode-(\d+)/)[1]);
      const numB = parseInt(b.match(/episode-(\d+)/)[1]);
      return numA - numB;
    });

  const episodes = episodeFiles.map((f) =>
    JSON.parse(readFileSync(join(seriesEpisodesDir, f), "utf-8"))
  );

  const liveEpisodes = episodes.filter((ep) => ep.status === "live");
  totalEpisodes += liveEpisodes.length;

  // Update status to Airing if there are live episodes
  const status = liveEpisodes.length > 0 ? "Airing" : s.status;

  return {
    ...s,
    status,
    epCount: liveEpisodes.length,
    episodes: liveEpisodes,
  };
});

console.log(`Read ${totalEpisodes} episode(s) across ${series.length} series`);

// Generate data.ts
const output = `// AUTO-GENERATED by scripts/build-data.js — do not edit manually.
// Source: clients/${CLIENT}/series.json + series/*/episodes/*.json + shop.json

import type { Series, ShopProduct } from "./types";

export const SERIES: Series[] = ${JSON.stringify(seriesWithEpisodes, null, 2)};

export const SHOP: ShopProduct[] = ${JSON.stringify(shop.products, null, 2)};

export const SHOP_CATEGORIES = ${JSON.stringify(shop.categories)} as const;
export const BROWSE_TYPES = ${JSON.stringify(shop.browseTypes)} as const;

export function getSeriesBySlug(slug: string): Series | undefined {
  return SERIES.find((s) => s.id === slug);
}

export function getEpisodeBySlugs(
  seriesSlug: string,
  episodeSlug: string
): { series: Series; episode: (typeof SERIES)[0]["episodes"][0] } | undefined {
  const series = getSeriesBySlug(seriesSlug);
  if (!series) return undefined;
  const episode = series.episodes.find((e) => e.slug === episodeSlug);
  if (!episode) return undefined;
  return { series, episode };
}

export function getAllEpisodePaths(): {
  seriesSlug: string;
  episodeSlug: string;
}[] {
  const paths: { seriesSlug: string; episodeSlug: string }[] = [];
  for (const series of SERIES) {
    for (const ep of series.episodes) {
      if (ep.status === "live") {
        paths.push({ seriesSlug: series.id, episodeSlug: ep.slug });
      }
    }
  }
  return paths;
}
`;

writeFileSync(outFile, output, "utf-8");
console.log(`Generated: ${outFile}`);
