/**
 * Pre-build script: reads series.json, shop.json, and episode JSON files
 * from clients/pokemon-fables/ and generates src/lib/data.ts.
 *
 * Run before `next build` via the "prebuild" npm script.
 *
 * Usage: node scripts/build-data.js
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Hard-coded to pokemon-fables for now (only client)
const CLIENT = "pokemon-fables";
const clientDir = join(ROOT, "clients", CLIENT);
const outFile = join(ROOT, "src", "lib", "data.ts");

// Read series metadata
const series = JSON.parse(
  readFileSync(join(clientDir, "series.json"), "utf-8")
);

// Read shop data
const shop = JSON.parse(readFileSync(join(clientDir, "shop.json"), "utf-8"));

// Read all episode files
const episodesDir = join(clientDir, "episodes");
const episodeFiles = readdirSync(episodesDir)
  .filter((f) => f.startsWith("episode-") && f.endsWith(".json"))
  .sort((a, b) => {
    const numA = parseInt(a.match(/episode-(\d+)/)[1]);
    const numB = parseInt(b.match(/episode-(\d+)/)[1]);
    return numA - numB;
  });

const episodes = episodeFiles.map((f) =>
  JSON.parse(readFileSync(join(episodesDir, f), "utf-8"))
);

console.log(`Read ${episodes.length} episode(s), ${series.length} series`);

// Attach episodes to the "Airing" series
const seriesWithEpisodes = series.map((s) => {
  if (s.status === "Airing") {
    const liveEpisodes = episodes.filter((ep) => ep.status === "live");
    return {
      ...s,
      epCount: liveEpisodes.length,
      episodes: liveEpisodes,
    };
  }
  return {
    ...s,
    epCount: 0,
    episodes: [],
  };
});

// Generate data.ts
const output = `// AUTO-GENERATED by scripts/build-data.js — do not edit manually.
// Source: clients/${CLIENT}/series.json + episodes/*.json + shop.json

import type { Series, ShopProduct } from "./types";

export const SERIES: Series[] = ${JSON.stringify(seriesWithEpisodes, null, 2)};

export const SHOP: ShopProduct[] = ${JSON.stringify(shop.products, null, 2)};

export const SHOP_CATEGORIES = ${JSON.stringify(shop.categories)} as const;
export const BROWSE_TYPES = ${JSON.stringify(shop.browseTypes)} as const;

export function getSeriesBySlug(slug: string): Series | undefined {
  return SERIES.find((s) => s.id === slug);
}

export function getEpisodeBySlugs(
  seriesSlug: string,
  episodeSlug: string
): { series: Series; episode: (typeof SERIES)[0]["episodes"][0] } | undefined {
  const series = getSeriesBySlug(seriesSlug);
  if (!series) return undefined;
  const episode = series.episodes.find((e) => e.slug === episodeSlug);
  if (!episode) return undefined;
  return { series, episode };
}

export function getAllEpisodePaths(): {
  seriesSlug: string;
  episodeSlug: string;
}[] {
  const paths: { seriesSlug: string; episodeSlug: string }[] = [];
  for (const series of SERIES) {
    for (const ep of series.episodes) {
      if (ep.status === "live") {
        paths.push({ seriesSlug: series.id, episodeSlug: ep.slug });
      }
    }
  }
  return paths;
}
`;

writeFileSync(outFile, output, "utf-8");
console.log(`Generated: ${outFile}`);
